version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./mysql:/var/lib/mysql
  demo:
    image: demo-app
    depends_on:
      - mysql
    ports:
      - 8080:8080